export type Product = {
	_id: string;
	name: string;
	full_name: string;
	manufacturer: string;
	stock: number;
	free_shipping: boolean;
	shipped_by: string;
	cores: number;
	base_clock: number;
	boost_clock: number;
	l3_cache: number;
	tdp: number;
	price: number;
	discount: number;
	integrated_graphics: boolean;
	reviews: number;
	stars: number;
	release_date: Date;
	best_sellers: [{ seller: string; price: number; ratings: number; pos_review_percent: number }];
	image: string[];
	details: string[];
};